import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
<<<<<<< HEAD
import Header from "./components/homepage/Header";
import Footer from "./components/homepage/Footer";
=======
>>>>>>> 6aedb29 (commit)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <AuthProvider>
<<<<<<< HEAD
          <Header />
            {children}
          <Footer />
=======
          {children}
>>>>>>> 6aedb29 (commit)
        </AuthProvider>
      </body>
    </html>
  );
}
